name: Main workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Dependency instalation
        run: npm ci

      # I split types check and build to two different command,
      # because I do not want to have tests in docker container
      - name: Checking typescript types
        run: npm run types-check

      - name: Linting
        run: npm run lint

      - name: Integration tests
        run: npm run test

      - name: Checking typescript types and build app
        run: npm run build

      - name: Checking typescript types and build app
        run: npm run build

      # semantic-release release only from master branch, so do not be worry
      - name: Publish to Github Marketplace
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
