name: Quality check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Dependency instalation
        run: npm ci

      # I split types check and build to two different command,
      # because I do not want to have tests in docker container
      - name: Checking typescript types
        run: npm run types-check

      - name: Linting
        run: npm run lint

      - name: Integration tests
        run: npm run test

      - name: Checking typescript types and build app
        run: npm run build
