name: Run action

on: push

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Trigger script to send proper slack message
        uses: ./
        with:
          ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
          BASE_BRANCH: develop
          HEAD_BRANCH: master
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          SLACK_CHANNEL_WEBHOOK_URL: ${{ secrets.SLACK_CHANNEL_WEBHOOK_URL }}
          # Expected values [ true, false ]
          SEND_NOTIFICATION_EVEN_ALL_SUCCESS: false
